version: '2'
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://ordersapp@postgres/orders
    networks:
      - default
      - payments_default
    external_links:
      - payments_web_1:payments.local
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: ordersapp
      POSTGRES_PASSWORD: orderspass
      POSTGRES_DB: orders
networks:
  payments_default:
    external: true
